### ISSUE TITLE
spring-boot-starter-parent 3.0.0-M2 jar包问题

### ISSUE THREAD

**Issue by Alien-XXX** [digitalsonic/learning-spring-samples#1]
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.0-M2</version>
		<relativePath/> 
</parent>
这个版本在maven仓库好像是拉不到了, 我尝试切换更高的版本 , 有一些类是不向下兼容的 ,  请问作者可以提供这个包么 , 或者切换 一个版本.

**Comment by digitalsonic** [comment]
3.0.0-m2的包需要到Spring Milestone的仓库里拉取，我们在pom.xml里有添加如下的依赖，你可以检查下自己的pom.xml里是否有添加。

	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

**Comment by Alien-XXX** [comment]
> 3.0.0-m2的包需要到Spring Milestone的仓库里拉取，我们在pom.xml里有添加如下的依赖，你可以检查下自己的pom.xml里是否有添加。3.0.0-m2的包需要到春天里程碑的仓库里拉取,我们在pom.xml里有添加如下的依赖,你可以检查下自己的pom.xml里是否有添加。
> 
> ```
> <repositories>
> 	<repository>
> 		<id>spring-milestones</id>
> 		<name>Spring Milestones</name>
> 		<url>https://repo.spring.io/milestone</url>
> 		<snapshots>
> 			<enabled>false</enabled>
> 		</snapshots>
> 	</repository>
> </repositories>
> <pluginRepositories>
> 	<pluginRepository>
> 		<id>spring-milestones</id>
> 		<name>Spring Milestones</name>
> 		<url>https://repo.spring.io/milestone</url>
> 		<snapshots>
> 			<enabled>false</enabled>
> 		</snapshots>
> 	</pluginRepository>
> </pluginRepositories>
> ```
Unresolved plugin: 'org.springframework.boot:spring-boot-maven-plugin:3.0.0-M2'
